name: Build Media3 ExoPlayer Demo

on:
  workflow_dispatch:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build demo APK
        run: ./gradlew :media3:demo:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: demo-debug-apk
          path: media3/demo/build/outputs/apk/debug/demo-debug.apk
